Make install exit with error message if no argument is given

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-# Setup vars
-if [[ "$*" == *--help* ]]; then
+# Validation/Usage
+print-usage() {
   echo -e "NAME\n\t$0 - install dotfiles"
-  echo -e "SYNOPSIS\n\t$0 [--help] [<bundle>...] [layer...]\n"
+  echo -e "SYNOPSIS\n\t$0 [--help] (<bundle> | <layer>) [<bundle>...] [<layer>...]\n"
   echo -e "OPTIONS\n"
   echo -e "\t<layer>..."
   echo -e "\t    Folders to be stowed to ~ (not starting with '@')."
@@ -13,12 +13,24 @@ if [[ "$*" == *--help* ]]; then
   echo -e "EXAMPLE\n\t$0 @minimal @wsl ptpython\n"
   echo -en "NOTES\n\tEnv vars SKIP_PACKAGES and VERBOSE can be used to "
   echo -e "control the installation.\n"
+}
+
+if [[ "$*" == *--help* ]]; then
+  print-usage
   exit 0
 fi
 
+if [ "$#" -lt 1 ]; then
+  echo -e "************************ MISSING ARGUMENTS ************************"
+  echo -e "*    Please provide at least one argument (e.g. \"@default\")       *"
+  echo -e "*******************************************************************\n\n"
+  print-usage
+  exit 1
+fi
+
+# Setup vars
 DIR=$(pwd)
 args=($@)
-[ "$#" -ge 1 ] || args=("@default")
 bundles=($({ IFS=$'\n'; echo "${args[*]}"; } | grep '@'))
 extra_layers=($({ IFS=$'\n'; echo "${args[*]}"; } | grep -v '@'))
 
